### ISSUE TITLE
LaSRC Usage

### ISSUE THREAD

**Issue by AhmedShamli** [yannforget/conda-recipes#2]
Hi, Thank you for putting this together. 
I have install it correctly using the provided installation instructions and was able to run "convert_lpgs_to_espa" to convert the downloaded L1 product to ESPA format. 
My understanding is that I need to update the auxiliary data before running  LaSRC, and the USGS repository refers to the updatelads.py script for doing so.
Is the updatelads.py included in this package or I need to download it!!

Thanks,

**Comment by yannforget** [comment]
Hi,
Yes, to use LaSRC you need some data derived from MODIS products. I didn't include the python2 scripts from USGS, but you can [download it](https://github.com/USGS-EROS/espa-surface-reflectance/blob/master/lasrc/landsat_aux/scripts/updatelads.py) and run it manually:

`python2 updatelads.py --help`

You will need an username and a password to access the `ladssci.nascom.nasa.gov` server, as described [here](https://github.com/USGS-EROS/espa-surface-reflectance/tree/master/lasrc#auxiliary-data-updates) (just say that you need an access in order to use the LaSRC software).

Personally, I do not like the way this script works. I use another homemade script for auxiliary data acquisition that only downloads the data needed for a specific date. I will make it public soon

**Comment by AhmedShamli** [comment]
Thank you. that was really helpful.

**Comment by yannforget** [comment]
Hi Ahmed,

Just an update on this topic: USGS just released a new version of the script that doesn't need any username/password and uses only publicly accessible servers:

https://github.com/USGS-EROS/espa-surface-reflectance/blob/laads_hotrelease/lasrc/landsat_aux/scripts/updatelads.py

So if you are still facing this issue, just use this script :)

Yann.

**Comment by AhmedShamli** [comment]
Hi Yann,

Awesome, I will give it a try.
Thank you.

Ahmed
