### ISSUE TITLE
Running ledapds

### ISSUE THREAD

**Issue by ahornero** [yannforget/conda-recipes#3]
Hi, first of all thank you very much for this awesome package, it is great!

I can find all the binary files except do_ledaps.py, how can I run it after installing it?

Thanks in advance. Regards,

Alberto.

**Comment by yannforget** [comment]
Hi,

Thanks for reporting it, I forgot to include it (I don't use this script myself).

However, you can download it directly from upstream ([here](https://raw.githubusercontent.com/USGS-EROS/espa-surface-reflectance/master/ledaps/ledapsSrc/scripts/do_ledaps.py)) and run it like any python script : 

``` sh
python do_ledaps.py --help
```

Use `python2` instead of `python` if you are using a distribution that use `python3` as default.

**Comment by ahornero** [comment]
Hi Yann,

Thanks for you quick answer. So, do you also recommend Anaconda with Python 2.7 version instead of 3 for this purpose?

Regarding the Anticiallary files, should I download them separately and create the environment variable in the PATH or this is something also included within your container?

Thanks again. Regards,

Alberto.

**Comment by yannforget** [comment]
The Anaconda python version should not matter as long as you run a script with `python2 <script.py>`. If `python2` is not available in your Anaconda environment your shell will call the one installed in your system. So as long as you have Python 2 installed somewhere in your PATH you shouldn't have any issue.

Regarding the auxiliary files: the conda recipe only provides the binaries, so you still have to download the auxiliary files and set the environment variables yourself (as documented [here](https://github.com/USGS-EROS/espa-surface-reflectance/tree/master/ledaps)). IIRC only `LEDAPS_AUX_DIR` and `ESPA_LAND_MASS_POLYGON` (not sure for this one).

You are welcome :)

**Comment by ahornero** [comment]
Hi Yann, thanks again. Everything was clarified! 👍
